spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

server:
  port: 8080
  servlet:
    context-path: /account-management

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:https://run.mocky.io/v3/9769bf3a-b0b6-477a-9ff5-91f63010c9d3}